#!/bin/bash

# Pedir nombre de usuario
read -p "Ingrese el nombre de usuario: " u

# Validar si el usuario ya existe
if id "$u" >/dev/null 2>&1; then
    echo "El usuario $u ya existe. Por favor, elija otro nombre de usuario."
    exit 1
fi

# Crear usuario
adduser "$u"

# Verificar si se creó correctamente
if [ $? -eq 0 ]; then
    # Añadir al grupo sudo
    usermod -aG sudo "$u"
    echo "El usuario $u ha sido creado y añadido al grupo sudo."
else
    echo "Error al crear el usuario $u."
fi